apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stock-scanner.fullname" . }}-secret
  labels:
    {{- include "stock-scanner.labels" . | nindent 4 }}
type: Opaque
data:
  API_KEY: {{ .Values.secret.apiKey | b64enc | quote }}
  TOKEN: {{ .Values.secret.token | b64enc | quote }}
  USER_TOKEN: {{ .Values.secret.userToken | b64enc | quote }}
  {{- range $key, $value := .Values.secret.extra }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }} 