{{- $frontendFullname := printf "%s-frontend" (include "stock-scanner.fullname" .) }}
{{- $backendFullname := printf "%s-backend" (include "stock-scanner.fullname" .) }}

---
# 前端服务
apiVersion: v1
kind: Service
metadata:
  name: {{ $frontendFullname }}
  labels:
    {{- include "stock-scanner.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "stock-scanner.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend

---
# 后端服务
apiVersion: v1
kind: Service
metadata:
  name: {{ $backendFullname }}
  labels:
    {{- include "stock-scanner.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "stock-scanner.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
