apiVersion: v1
kind: Service
metadata:
  name: {{ include "stock-scanner.fullname" . }}
  labels:
    {{- include "stock-scanner.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port | default 80 }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.backendPort | default 8888 }}
      targetPort: 8888
      protocol: TCP
      name: backend
  selector:
    {{- include "stock-scanner.selectorLabels" . | nindent 4 }}
