openapi: 3.0.3
info:
  title: 股票分析系统 API
  version: 1.0.0
  description: |
    股票分析系统的OpenAPI接口文档。
    所有接口均需通过Bearer Token鉴权（即HTTP Header中带`Authorization: Bearer <API_KEY>`）。
servers:
  - url: http://localhost:8888
    description: 本地开发环境
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    AnalysisRequest:
      type: object
      required:
        - stock_code
        - market_type
      properties:
        stock_code:
          type: string
          description: 股票代码
          example: "600000"
        market_type:
          type: string
          description: 市场类型（A, HK, US, ETF, LOF）
          example: "A"
        stream:
          type: boolean
          description: 是否流式返回
          default: false
    AnalysisResponse:
      type: object
      properties:
        stock_code:
          type: string
        status:
          type: string
          description: 分析状态 analyzing/completed/error
        analysis:
          type: string
          description: 分析结果（非流式模式下返回）
        ai_analysis_chunk:
          type: string
          description: 分析片段（流式模式下分块返回）
        score:
          type: integer
          description: 分析评分
        recommendation:
          type: string
          description: 投资建议
        error:
          type: string
          description: 错误信息
paths:
  /api/analysis:
    post:
      summary: 股票AI分析
      description: |
        对指定股票进行AI分析。
        支持流式和非流式两种模式。
        需在Header中携带`Authorization: Bearer <API_KEY>`。
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnalysisRequest'
      responses:
        '200':
          description: 分析结果
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnalysisResponse'
        '401':
          description: 未授权或API_KEY无效
        '400':
          description: 请求参数错误
        '500':
          description: 服务器内部错误
security:
  - BearerAuth: [] 