# Default values for stock-scanner.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

# 命名空间
nameOverride: "stock-scanner"
fullnameOverride: "stock-scanner"

# 后端服务配置
backend:
  image:
    repository: k8sf/stock-scanner
    pullPolicy: IfNotPresent
    tag: "0.1"
  service:
    type: ClusterIP
    port: 8888
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 512Mi
  livenessProbe:
    httpGet:
      path: /api/config
      port: 8888
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  readinessProbe:
    httpGet:
      path: /api/config
      port: 8888
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3
  env:
    - name: API_KEY
      value: "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"
    - name: API_URL
      value: "https://openrouter.ai/api"
    - name: API_MODEL
      value: "tngtech/deepseek-r1t-chimera:free"
    - name: API_TIMEOUT
      value: "60"
    - name: TOKEN
      value: "j3wYD9mO0je5yPm20vfqUnTqpeWjhLGRmIO5hcZNqDY="
    - name: ANNOUNCEMENT_TEXT
      value: "欢迎使用股票分析系统"
    - name: MODE
      value: "DEBUG"
    - name: LOG_LEVEL
      value: "TRACE"
    - name: USER_TOKEN
      value: "j3wYD9mO0je5yPm20vfqUnTqpeWjhLGRmIO5hcZNqDY="
    - name: TUSHARE_TOKEN
      value: "30dd89a41c53facb136d77f8ba652b5963fe96919483ac2a4a111a4f"
  persistence:
    enabled: true
    storageClass: ""
    accessMode: ReadWriteOnce
    size: 5Gi
    data:
      mountPath: /app/data
    logs:
      mountPath: /app/logs

# 服务配置
service:
  type: ClusterIP
  port: 80
  backendPort: 8888

imagePullSecrets: []

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# Ingress配置
ingress:
  enabled: true
  className: "traefik"
  annotations:
    kubernetes.io/ingress.class: traefik
  hosts:
    - host: stock-scanner.xiongjuli.com
      paths:
        - path: /
          pathType: Prefix
          service: backend
  tls:
    - secretName: xiongjuli-com-tls
      hosts:
        - stock-scanner.xiongjuli.com

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# 持久卷配置
persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 5Gi
  data:
    mountPath: /app/data
  logs:
    mountPath: /app/logs

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

# 资源配置
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 512Mi

nodeSelector: {}

tolerations: []

affinity: {}
